USE Produits;

INSERT INTO Categorie VALUES (1,"corbeille");
INSERT INTO Categorie VALUES (2,"intérieur");
INSERT INTO Categorie VALUES (3,"extérieur");


INSERT INTO Poubelle VALUES (1,"Dunkelgruen",35,192,1);
INSERT INTO Poubelle VALUES (2,"Woodrow",44.50,347,1);
INSERT INTO Poubelle VALUES (3,"Mateo",19.25,415,1);
INSERT INTO Poubelle VALUES (4,"Velpabin",54.90,175,1);
INSERT INTO Poubelle VALUES (5,"Metal",55,58,1);
INSERT INTO Poubelle VALUES (6,"Exacompta",7.90,854,1);
INSERT INTO Poubelle VALUES (7,"Andromeda",750,124,2);
INSERT INTO Poubelle VALUES (8,"Ark",2,541,2);
INSERT INTO Poubelle VALUES (9,"Atmosphera",60,687,2);
INSERT INTO Poubelle VALUES (10,"Push",120,743,2);
INSERT INTO Poubelle VALUES (11,"Decor",230,419,2);
INSERT INTO Poubelle VALUES (12,"Collecteur",200,241,2);
INSERT INTO Poubelle VALUES (13,"Coogee",350,75,3);
INSERT INTO Poubelle VALUES (14,"Hanko",1250,41,3);
INSERT INTO Poubelle VALUES (15,"Rossignol",337,267,3);
INSERT INTO Poubelle VALUES (16,"Tulipe",215,78,3);
INSERT INTO Poubelle VALUES (17,"Conteneur",180,468,3);
INSERT INTO Poubelle VALUES (18,"GrandConteneur",310,55,3);


INSERT INTO Couleur VALUES(1,"bleu","../doc/poubelle/corbeille/dunkelgruen/dunkelgruen-35-bleu.png");
INSERT INTO Couleur VALUES(2,"rouge","../doc/poubelle/corbeille/dunkelgruen/dunkelgruen-35-rouge.png");
INSERT INTO Couleur VALUES(3,"blanc","../doc/poubelle/corbeille/dunkelgruen/dunkelgruen-35-blanc.png");
INSERT INTO Couleur VALUES(4,"beige","../doc/poubelle/corbeille/dunkelgruen/dunkelgruen-35-beige.png");
INSERT INTO Couleur VALUES(5,"blanc","../doc/poubelle/corbeille/wooddrow/wooddrow-44,50-blanche.png");
INSERT INTO Couleur VALUES(6,"beige","../doc/poubelle/corbeille/wooddrow/wooddrow-44,50-beige.png");
INSERT INTO Couleur VALUES(7,"vert","../doc/poubelle/corbeille/wooddrow/wooddrow-44,50-verte.png");
INSERT INTO Couleur VALUES(8,"noir","../doc/poubelle/corbeille/wooddrow/wooddrow-44,50-gris.png");
INSERT INTO Couleur VALUES(9,"bleu","../doc/poubelle/corbeille/mateo/mateo-19,25.png");
INSERT INTO Couleur VALUES(10,"noir","../doc/poubelle/corbeille/velpabin/velpabin-54_90.png");
INSERT INTO Couleur VALUES(11,"gris","../doc/poubelle/corbeille/metalA/metalA-55.png");
INSERT INTO Couleur VALUES(12,"bleu","../doc/poubelle/corbeille/exacompta/exacompta-7,90-bleu.png");
INSERT INTO Couleur VALUES(13,"noir","../doc/poubelle/corbeille/exacompta/exacompta-7,90-noir.png");
INSERT INTO Couleur VALUES(14,"rouge","../doc/poubelle/corbeille/exacompta/exacompta-7,90-rouge.png");
INSERT INTO Couleur VALUES(15,"vert","../doc/poubelle/corbeille/exacompta/exacompta-7,90-vert.png");
INSERT INTO Couleur VALUES(16,"vert","../doc/poubelle/intérieur/andromeda/andromeda-750-vert-bleu.png");
INSERT INTO Couleur VALUES(17,"blanc","../doc/poubelle/intérieur/andromeda/andromeda-750-blanc-bleu.png");
INSERT INTO Couleur VALUES(18,"jaune","../doc/poubelle/intérieur/andromeda/andromeda-750-jaune-blanc.png");
INSERT INTO Couleur VALUES(19,"bleu","../doc/poubelle/intérieur/andromeda/andromeda-750-jaune-bleu.png");
INSERT INTO Couleur VALUES(20,"blanc","../doc/poubelle/intérieur/ark/ark-1-blanc.png");
INSERT INTO Couleur VALUES(21,"noir","../doc/poubelle/intérieur/ark/ark-1-gris.png");
INSERT INTO Couleur VALUES(22,"rose","../doc/poubelle/intérieur/ark/ark-1-rose.png");
INSERT INTO Couleur VALUES(23,"vert","../doc/poubelle/intérieur/ark/ark-1-vert.png");
INSERT INTO Couleur VALUES(24,"noir","../doc/poubelle/intérieur/atmosphera/atmosphera-60-noir.png");
INSERT INTO Couleur VALUES(25,"blanc","../doc/poubelle/intérieur/atmosphera/atmosphera-60-blanche.png");
INSERT INTO Couleur VALUES(26,"rouge","../doc/poubelle/intérieur/atmosphera/atmosphera-60-rouge.png");
INSERT INTO Couleur VALUES(27,"gris","../doc/poubelle/intérieur/push/push-120-gris.png");
INSERT INTO Couleur VALUES(28,"rose","../doc/poubelle/intérieur/push/push-120-rose.png");
INSERT INTO Couleur VALUES(29,"bleu","../doc/poubelle/intérieur/push/push-120-bleu.png");
INSERT INTO Couleur VALUES(30,"rouge","../doc/poubelle/intérieur/push/push-120-rouge.png");
INSERT INTO Couleur VALUES(31,"gris","../doc/poubelle/intérieur/decor/decor-230-argent.jpg");
INSERT INTO Couleur VALUES(32,"vert","../doc/poubelle/intérieur/collecteur/collecter-200-vert.png");
INSERT INTO Couleur VALUES(33,"jaune","../doc/poubelle/intérieur/collecteur/collecter-200-jaune.png");
INSERT INTO Couleur VALUES(34,"bleu","../doc/poubelle/intérieur/collecteur/collecter-200-bleu.png");
INSERT INTO Couleur VALUES(35,"rouge","../doc/poubelle/intérieur/collecteur/collecter-200-rouge.png");
INSERT INTO Couleur VALUES(36,"gris","../doc/poubelle/intérieur/collecteur/collecter-200-gris.png");
INSERT INTO Couleur VALUES(37,"vert","../doc/poubelle/extérieur/coogee/coogee-350-vert-rouge.png");
INSERT INTO Couleur VALUES(38,"bleu","../doc/poubelle/extérieur/coogee/coogee-350-bleu-jaune.png");
INSERT INTO Couleur VALUES(39,"jaune","../doc/poubelle/extérieur/Hanko/Hanko-1250-jaune.png");
INSERT INTO Couleur VALUES(40,"vert","../doc/poubelle/extérieur/Hanko/Hanko-1250-verte.png");
INSERT INTO Couleur VALUES(41,"bleu","../doc/poubelle/extérieur/Hanko/Hanko-1250-bleu.png");
INSERT INTO Couleur VALUES(42,"gris","../doc/poubelle/extérieur/Hanko/Hanko-1250-gris.png");
INSERT INTO Couleur VALUES(43,"bleu","../doc/poubelle/extérieur/rossignol/rossignol-337-bleu.png");
INSERT INTO Couleur VALUES(44,"gris","../doc/poubelle/extérieur/rossignol/rossignol-337-gris.png");
INSERT INTO Couleur VALUES(45,"vert","../doc/poubelle/extérieur/tulipe/tulipe-215-vert.png");
INSERT INTO Couleur VALUES(46,"noir","../doc/poubelle/extérieur/tulipe/tulipe-215-noir.png");
INSERT INTO Couleur VALUES(47,"jaune","../doc/poubelle/extérieur/conteneur/conteneur-180-jaune.png");
INSERT INTO Couleur VALUES(48,"bleu","../doc/poubelle/extérieur/conteneur/conteneur-180-bleu.png");
INSERT INTO Couleur VALUES(49,"vert","../doc/poubelle/extérieur/conteneur/conteneur-180-vert.png");
INSERT INTO Couleur VALUES(50,"rouge","../doc/poubelle/extérieur/conteneur/conteneur-180-rouge.png");
INSERT INTO Couleur VALUES(51,"bleu","../doc/poubelle/extérieur/Gconteneur/Gconteneur-310-bleu.png");

INSERT INTO Posseder VALUES (1,1);
INSERT INTO Posseder VALUES (1,2);
INSERT INTO Posseder VALUES (1,3);
INSERT INTO Posseder VALUES (1,4);
INSERT INTO Posseder VALUES (2,5);
INSERT INTO Posseder VALUES (2,6);
INSERT INTO Posseder VALUES (2,7);
INSERT INTO Posseder VALUES (2,8);
INSERT INTO Posseder VALUES (3,9);
INSERT INTO Posseder VALUES (4,10);
INSERT INTO Posseder VALUES (5,11);
INSERT INTO Posseder VALUES (6,12);
INSERT INTO Posseder VALUES (6,13);
INSERT INTO Posseder VALUES (6,14);
INSERT INTO Posseder VALUES (6,15);
INSERT INTO Posseder VALUES (7,16);
INSERT INTO Posseder VALUES (7,17);
INSERT INTO Posseder VALUES (7,18);
INSERT INTO Posseder VALUES (7,19);
INSERT INTO Posseder VALUES (8,20);
INSERT INTO Posseder VALUES (8,21);
INSERT INTO Posseder VALUES (8,22);
INSERT INTO Posseder VALUES (8,23);
INSERT INTO Posseder VALUES (9,24);
INSERT INTO Posseder VALUES (9,25);
INSERT INTO Posseder VALUES (9,26);
INSERT INTO Posseder VALUES (10,27);
INSERT INTO Posseder VALUES (10,28);
INSERT INTO Posseder VALUES (10,29);
INSERT INTO Posseder VALUES (10,30);
INSERT INTO Posseder VALUES (11,31);
INSERT INTO Posseder VALUES (12,32);
INSERT INTO Posseder VALUES (12,33);
INSERT INTO Posseder VALUES (12,34);
INSERT INTO Posseder VALUES (12,35);
INSERT INTO Posseder VALUES (12,36);
INSERT INTO Posseder VALUES (13,37);
INSERT INTO Posseder VALUES (13,38);
INSERT INTO Posseder VALUES (14,39);
INSERT INTO Posseder VALUES (14,40);
INSERT INTO Posseder VALUES (14,41);
INSERT INTO Posseder VALUES (14,42);
INSERT INTO Posseder VALUES (15,43);
INSERT INTO Posseder VALUES (15,44);
INSERT INTO Posseder VALUES (16,45);
INSERT INTO Posseder VALUES (16,46);
INSERT INTO Posseder VALUES (17,47);
INSERT INTO Posseder VALUES (17,48);
INSERT INTO Posseder VALUES (17,49);
INSERT INTO Posseder VALUES (17,50);
INSERT INTO Posseder VALUES (18,51);

INSERT INTO Utilisateur VALUES(1,"valentin@serres.fr","gaming");
INSERT INTO Utilisateur VALUES(2,"ugo@latry.fr","paularis");